In [1]:
import numpy as np

In [2]:
price_per_unit = np.array([1000,400,1200])#is same as: price_per_unit = np.array([[1000,400,1200],[1000,400,1200],[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [3]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [4]:
np.dot(units,price_per_unit,) #or use, res=price_per_unit@units

array([106000,  27000,  12400])

In [5]:
price_per_unit@units

array([34400, 50000, 64400])

In [6]:
np.ones(2,)

array([1., 1.])

In [8]:
np.ones((1,2))

array([[1., 1.]])

In [9]:
np.ones(2,).T

array([1., 1.])

In [10]:
np.ones((1,2)).T

array([[1.],
       [1.]])

In [ ]:
np.array